config/routes.rb
BecskeReg2015::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/guru_yoga"

  get "static_pages/karma_paksi"

  get "static_pages/programs"

  get "static_pages/information"

  root :to => 'static_pages#home'

  get "sessions/new"

  scope ":locale" do
    resources :users
    resources :children
    resources :registrations
    resources :meals do
      resources :meal_report
    end
    resources :programs
    resources :payments
    resources :travels do
      resources :travel_report
    end
    resources :sessions
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/travel.rb
class Travel < ActiveRecord::Base
  belongs_to :user
  #attr_accessible :arrival, :arrival_seats, :bus_trip, :departure, :departure_seats, :flight_date, :flight_number, :user_id
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  # GET /travels
  # GET /travels.json

  before_action :set_travel, only: [:show, :edit, :update, :destroy]
  def index
    @travels = Travel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @travels }
    end
  end

  # GET /travels/1
  # GET /travels/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @travel }
    end
  end

  # GET /travels/new
  # GET /travels/new.json
  def new
    @travel = Travel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @travel }
    end
  end

  # GET /travels/1/edit
  def edit
  end

  # POST /travels
  # POST /travels.json
  def create
    @travel = Travel.new(travel_params)

    respond_to do |format|
      if @travel.save
        format.html { redirect_to @travel, notice: 'Travel was successfully created.' }
        format.json { render json: @travel, status: :created, location: @travel }
      else
        format.html { render action: "new" }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /travels/1
  # PUT /travels/1.json
  def update


    respond_to do |format|
      if @travel.update_attributes(travel_params)
        format.html { redirect_to @travel, notice: 'Travel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travels/1
  # DELETE /travels/1.json
  def destroy

    @travel.destroy

    respond_to do |format|
      format.html { redirect_to travels_url }
      format.json { head :no_content }
    end
  end

  private
  def set_travel
      @travel = Travel.find(params[:id])
  end

  def travel_params
      params.require(:travel).permit(:arrival, :arrival_seats, :bus_trip, :departure, :departure_seats, :flight_date, :flight_number, :user_id)
  end

end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/_form.html.erb
<%= form_for(@travel) do |f| %>
  <% if @travel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@travel.errors.count, "error") %> prohibited this travel from being saved:</h2>

      <ul>
      <% @travel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <fieldset>
  <div class="field">
    <%= f.label :bus_trip %><br />
    <%= f.check_box :bus_trip, :class => 'bus_trip' %>
  </div>
  <div class="field">
    <%= f.label :arrival %><br />
    <%= f.select(:arrival, [['2013-07-12 11:00', '2013-07-12 11:00'], ['2013-07-12 11:00', '2013-07-12 15:00']]) %>
  </div>
  <div class="field">
    <%= f.label :arrival_seats %><br />
    <%= f.select(:arrival_seats, (0...6), {}, :class => 'seats') %>
  </div>
  <div class="field">
    <%= f.label :departure %><br />
    <%= f.select(:departure, [['2013-07-18 20:00', '2013-07-18 20:00'],['2013-07-18 20:00', '2013-07-18 20:00']]) %>
  </div>
  <div class="field">
    <%= f.label :departure_seats %><br />
    <%= f.select(:departure_seats, (0...6), {}, :class => 'seats') %>
  </div>
  <div class="field">
    <%= f.label :flight_date %><br />
    <%= f.datetime_select :flight_date %>
  </div>
  <div class="field">
    <%= f.label :flight_number %><br />
    <%= f.text_field :flight_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</fieldset>

app/views/travels/edit.html.erb
<h1>Editing travel</h1>

<%= render 'form' %>

<%= link_to 'Show', @travel %> |
<%= link_to 'Back', travels_path %>

app/views/travels/index.html.erb
<h1>Listing travels</h1>

<table>
  <tr>
    <th>Arrival</th>
    <th>Bus trip</th>
    <th>Arrival seats</th>
    <th>Departure seats</th>
    <th>Departure</th>
    <th>Flight number</th>
    <th>Flight date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @travels.each do |travel| %>
  <tr>
    <td><%= travel.arrival %></td>
    <td><%= travel.bus_trip %></td>
    <td><%= travel.arrival_seats %></td>
    <td><%= travel.departure_seats %></td>
    <td><%= travel.departure %></td>
    <td><%= travel.flight_number %></td>
    <td><%= travel.flight_date %></td>
    <td><%= link_to 'Show', travel %></td>
    <td><%= link_to 'Edit', edit_travel_path(travel) %></td>
    <td><%= link_to 'Destroy', travel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Travel', new_travel_path %>

app/views/travels/new.html.erb
<h1>New travel</h1>

<%= render 'form' %>

<%= link_to 'Back', travels_path %>

app/views/travels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Arrival:</b>
  <%= @travel.arrival %>
</p>

<p>
  <b>Bus trip:</b>
  <%= @travel.bus_trip %>
</p>

<p>
  <b>Arrival seats:</b>
  <%= @travel.arrival_seats %>
</p>

<p>
  <b>Departure seats:</b>
  <%= @travel.departure_seats %>
</p>

<p>
  <b>Departure:</b>
  <%= @travel.departure %>
</p>

<p>
  <b>Flight number:</b>
  <%= @travel.flight_number %>
</p>

<p>
  <b>Flight date:</b>
  <%= @travel.flight_date %>
</p>


<%= link_to 'Edit', edit_travel_path(@travel) %> |
<%= link_to 'Back', travels_path %>