config/routes.rb
BecskeReg2015::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/guru_yoga"

  get "static_pages/karma_paksi"

  get "static_pages/programs"

  get "static_pages/information"

  root :to => 'static_pages#home'

  get "sessions/new"

  scope ":locale" do
    resources :users
    resources :children
    resources :registrations
    resources :meals do
      resources :meal_report
    end
    resources :programs
    resources :payments
    resources :travels do
      resources :travel_report
    end
    resources :sessions
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/program.rb
class Program < ActiveRecord::Base
  #attr_accessible :exchange_rate, :price_discount, :price_full, :price_full_eur, :price_discount_eur, :program_name_en, :program_name_hu, :event_date

  has_many :registrations
  has_many :users, :through => :registrations
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json

  before_action :set_program, only: [:show, :edit, :update, :destroy]
  def index
    @programs = Program.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update

    respond_to do |format|
      if @program.update_attributes(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end

  private
  def set_program
    @program = Program.find(params[:id])
  end

  def program_params
    params.require(:program).permit(:exchange_rate, :price_discount, :price_full, :price_full_eur, :price_discount_eur, :program_name_en, :program_name_hu, :event_date)
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :event_date %><br/>
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :program_name_hu %><br />
    <%= f.text_field :program_name_hu %>
  </div>
  <div class="field">
    <%= f.label :program_name_en %><br />
    <%= f.text_field :program_name_en %>
  </div>
  <div class="field">
    <%= f.label :price_full %><br />
    <%= f.number_field :price_full %>
  </div>
  <div class="field">
    <%= f.label :price_full_eur %><br />
    <%= f.number_field :price_full_eur %>
  </div>
  <div class="field">
    <%= f.label :price_discount_eur %><br />
    <%= f.number_field :discount_eur %>
  </div>
  <div class="field">
    <%= f.label :price_discount %><br />
    <%= f.number_field :price_discount %>
  </div>
  <div class="field">
    <%= f.label :exchange_rate %><br />
    <%= f.number_field :exchange_rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<table>
  <tr>
    <th>Program event date</th>
    <th>Program name hu</th>
    <th>Program name en</th>
    <th>Price full</th>
    <th>Price full EURO</th>
    <th>Price discount EURO</th>
    <th>Price discount</th>
    <th>Exchange rate</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

<% @programs.each do |program| %>
  <tr>
    <td><%= program.event_date %></td>
    <td><%= program.program_name_hu %></td>
    <td><%= program.program_name_en %></td>
    <td><%= program.price_full %></td>
    <td><%= program.price_full_eur %></td>
    <td><%= program.price_discount_eur %></td>
    <td><%= program.price_discount %></td>
    <td><%= program.exchange_rate %></td>
    <td><%= link_to 'Show', program %></td>
    <td><%= link_to 'Edit', edit_program_path(program) %></td>
    <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Program date:</b>
  <%= @program.event_date %>
</p>
<p>
  <b>Program name hu:</b>
  <%= @program.program_name_hu %>
</p>

<p>
  <b>Program name en:</b>
  <%= @program.program_name_en %>
</p>

<p>
  <b>Price full:</b>
  <%= @program.price_full %>
</p>

<p>
  <b>Price full Euro:</b>
  <%= @program.price_full_eur %>
</p>

<p>
  <b>Price discount Euro:</b>
  <%= @program.price_discount_eur %>
</p>

<p>
  <b>Price discount:</b>
  <%= @program.price_discount %>
</p>

<p>
  <b>Exchange rate:</b>
  <%= @program.exchange_rate %>
</p>


<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>