config/routes.rb
BecskeReg2015::Application.routes.draw do

  get "static_pages/home"

  get "static_pages/guru_yoga"

  get "static_pages/karma_paksi"

  get "static_pages/programs"

  get "static_pages/information"

  root :to => 'static_pages#home'

  get "sessions/new"

  scope ":locale" do
    resources :users
    resources :children
    resources :registrations
    resources :meals do
      resources :meal_report
    end
    resources :programs
    resources :payments
    resources :travels do
      resources :travel_report
    end
    resources :sessions
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :user

  validate :food_type, :meal_date, :meal_type, :presence => true
end

app/controllers/meals_controller.rb
class ChildrenController < ApplicationController
  # GET /children
  # GET /children.json

  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  def index
    @meals = Meal.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meals }
    end
  end

  # GET /meals/1
  # GET /meals/1.json
  def show

    @user = Person.find(user_id => User.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/1/edit
  def edit

  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Child was successfully created.' }
        format.json { render json: @meal, status: :created, location: @meal }
      else
        format.html { render action: "new" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update


    respond_to do |format|
      if @meal.update_attributes(meal_params)
        format.html { redirect_to @meal, notice: 'Child was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy

    @child.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end

  private
  def set_meal
    @meal = Meal.find(params[[:id])
  end

  def meal_params
    params.require(:meal).permit(:food_type, :meal_date, :meal_type, :user_id)
  end

end

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_type %><br />
    <%= f.text_field :food_type %>
  </div>
  <div class="field">
    <%= f.label :meal_date %><br />
    <%= f.number_field :meal_date %>
  </div>
  <div class="field">
    <%= f.label :meal_type %><br />
    <%= f.text_field :meal_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<h1>Listing meals</h1>

<table>
  <tr>
    <th>Foodtype</th>
    <th>Meal date</th>
    <th>Meal type</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meals.each do |meal| %>
  <tr>
    <td><%= meal.food_type %></td>
    <td><%= meal.date %></td>
    <td><%= meal.meal_type %></td>
    <td><%= meal.user.first_name %></td>
    <td><%= link_to 'Show', meal %></td>
    <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
    <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @meal.food_type %>
</p>

<p>
  <b>Age:</b>
  <%= @meal.meal_date %>
</p>

<p>
  <b>Language:</b>
  <%= @meal.meal_type %>
</p>

<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>